blog/authors.yml, docs/intro.md, docusaurus.config.js, sidebars.js, src/pages/index.js
This reverts commit e625bdf86aa3b786d93efbbfcb4bfe8d1dd5a091, reversing changes made to edc6dd1a70086c11b08c1a3b85b82740c6c9a1d6.
=> Revert "Merge branch 'experiment'"

docusaurus.config.js
1. Added Community Links
2. Added Social Media Links
3. Added Currently Ongoing Projects Links
=> [UPDATE] Added links in footer

CONTRIBUTORS.md
=> ADD CONTRIBUTORS - #66

docs/projects/docs-site/sidebar/adding-items.md, docs/projects/docs-site/sidebar/multiple-sidebars.md
- Added Borders in all images in the documentation of Docs Site
=> [CHANGES] Added Border in Images

src/components/HomepageFeatures/Hero.js
=> added parallax effect on hero images

src/css/custom.css, src/pages/markdown-page.md
- Changed Theme Colors in `/src/css/custom.css`
- Deleted redundant file in `/src/pages/`
=> [MAJOR] Website Theme updated wrt to logo of org

docs/projects/tcet-linux-website/getting-started.mdx
I have added the necessary details to 'getting started with TCET-Linux'
=> [ADDED]added documented getting started with tcet-linux

docs/projects/tcet-linux-website/about-tcet-linux-website.mdx
- Fixed the error in the URL, mentioned on 8 line of About page of TCET Linux Website Docs from (https://tcet-linux-website/) to (https://linux.tcetmumbai.in/).
=> [FIX] Fixed URL issue

package-lock.json, package.json, src/components/ProjectSection/index.js, src/components/UnderDevelopmentProjects/styles.module.css
padding of project section increased and width of under development project cards changed
Fixes issue #210
=> 210 padding issue

package-lock.json, src/components/Navbar/index.js, src/components/ProjectSection/ProjectPreview.js, src/components/ProjectSection/index.js
=> [FIX] Fixed the button border & Background Gradient issue

.github/workflows/build.yml
Changed Github Actions env from using secrets to using vars
N/A
=> [Fix] Changed Env from Secrets to Vars

docs/projects/tcet-linux/guides/yay-install.md, docs/projects/tcet-linux/guides/yay.md, sidebars.js
yay setup and how to install packages through yay
#308 
This documentation will help you out to install yay on your system
=> 308 tl yay install

docs/projects/tcet-linux/about-tcet-linux.md, sidebars.js
About TCET Linux
227 tl about tcet linux
Brief description about TCET Linux
=> 227 TL about tcet linux

docs/projects/tcet-linux/installation/troubleshoot-installation.md
Troubleshoot Installation
237
About Troubleshoot Installation
=> troubleshoot-installation

docs/about-tcetopensource.mdx, src/components/Footer/index.js, static/img/FooterSectionIcons/x.svg
Updated the icon for 'X' in Footer Section
Fixed: #319 
- Updated the logo of twitter from "Tweet" to "X" in the footer section of the file ``index.js``.
Here is the updated icon for "X" which was twitter's "tweet" icon:
=> [fixed] Updated the icon for 'X' in Footer Section

docs/projects/tcet-linux/contribute-tcet-linux.md
=> 234-contribute-tcet-linux

docs/projects/tcet-linux/references-credits.md
=> Added info in references and credits

docs/projects/tcet-linux/variants-releases.md
=> Added variant release info

docs/projects/tcet-linux/installation/installation-in-vm.md
Installation in VM
231
About Installation in VM
=> 231 tl new install in vm

docs/projects/tcet-linux/installation/requirements-download-verify.md
Requirements Download Verify
229
Descriptions about Requirements Download Verify
=> requirements download verify

docs/projects/tcet-linux/installation/creating-bootable-USB.md, docs/projects/tcet-linux/installation/partitioning.md, docs/projects/tcet-linux/installation/requirements-download-verify.md, sidebars.js
[333 Rename] installation in drive to creating a bootable usb
https://github.com/tcet-opensource/documentation/issues/333
=> [333 Rename]installation in drive to creating a bootable usb

docs/projects/tcet-linux/releases.md, sidebars.js
[TL] official release edit
https://github.com/tcet-opensource/documentation/issues/336
rename variant & release to release & Official Release Content
=> [TL] official release edit

docs/projects/tcet-linux/installation/installation-steps.md
TL added manaual partition erase disk warning & Image Center
https://github.com/tcet-opensource/documentation/issues/338
TL added manaual partition erase disk warning & Image Center
=> [TL] - Explain Manual Partitioning for Dual Boot & VM in installation steps 

docs/projects/tcet-linux/variant.md, sidebars.js
TECT Linux Variant
342
TCET Linux Variant
=> 342 tl tl variants

docs/projects/tcet-linux/guides/backup-restore-timeshift.md, sidebars.js
added backup resotre
https://github.com/tcet-opensource/documentation/issues/346
=> [TL] added backup resotre

docs/projects/tcet-linux/installation/installation-in-vm.md
[TL] edit installation-in-vm.md for arch linux
https://github.com/tcet-opensource/documentation/issues/334
[TL] edit installation-in-vm.md for arch linux
=> [TL] edit installation-in-vm.md for arch linux

docs/projects/tcet-linux/guides/chroot.md, sidebars.js
Chroot Documentation
347
Chroot Documentation
=> TL Chroot Guide

docusaurus.config.js
[Added] announcent for mumbaiFOSS2.0
Changed line 88 - 95 of ```documentation\docusaurus.config.js``` for announcement of the event MumbaiFOSS2.0 
comment this lines again after 27th April
=> [Added] announcent for mumbaiFOSS2.0
